[project]
name = "pixiv-notifs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gallery-dl>=1.30.10",
    "pynacl==1.6.1",
    "python-dateutil==2.9.0.post0",
    "requests==2.32.5",
    "tqdm==4.67.1",
]
